version: '3'
services:
  backend :
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kbtg
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: kbtg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"